### ISSUE TITLE
use d3r?

### ISSUE THREAD

**Issue by timelyportfolio** [fbreitwieser/sankeyD3#1]
Thanks so much for the invite to contribute.  I am slammed for the next month but still hope to be able to play, experiment, test, and add.  Have you seen [d3r](https://github.com/timelyportfolio/d3r)?  I think it offers several advantages especially in the `igraph` -> `d3` conversion.

**Comment by fbreitwieser** [comment]
d3r, that's a great package idea! Thanks @timelyportfolio , I'll be using it.

**Comment by timelyportfolio** [comment]
Would you be open to using `d3r` for the d3 dependencies?  Here is where I switched `sunburstR` to use `d3R` instead of `yaml` https://github.com/timelyportfolio/sunburstR/commit/be5361ddba9b68b27389a2aca03293c7806cc95f.

**Comment by fbreitwieser** [comment]
Thanks for the link to the change, it's really straightforward. And nice that it's on CRAN! I definitely am, I think it's a good idea to have the dependency in the package. Does using `d3r` also solve #4 ?
