### ISSUE TITLE
wish: option for node label color (e.g. fontColor)

### ISSUE THREAD

**Issue by ugroempi** [fbreitwieser/sankeyD3#13]
This would allow me to move node labels into colored nodes and still be readable. Being greedy, one could also have separate font options (most important: size; color might be the same) for the node labels and the node values.

Best, Ulrike

**Comment by fbreitwieser** [comment]
Hi Ulrike, sorry for the late answer, managed to implement something like that, now. See below:

```
library(sankeyD3)

# sankeyNetwork
URL <- "https://cdn.rawgit.com/christophergandrud/networkD3/master/JSONdata/energy.json"
Energy <- jsonlite::fromJSON(URL)

# Plot

Energy$nodes$font_color <- c("black", "red", "green")
Energy$nodes$font_size <- 5:10
sankeyNetwork(Links = Energy$links, Nodes = Energy$nodes, Source = "source",
              Target = "target", Value = "value", NodeID = "name",
              fontSize = 12, nodeWidth = 30, 
              NodeColor = "font_color",
              NodeFontColor = "font_color", NodeFontSize = "font_size")
```

![image](https://user-images.githubusercontent.com/516060/37696557-e4a5ed00-2cad-11e8-9fee-4c4723a21231.png)

**Comment by ugroempi** [comment]
Thank you!
Best, Ulrike
