### ISSUE TITLE
Does not work with 64-bit R

### ISSUE THREAD

**Issue by todd-d-desnz** [fbreitwieser/sankeyD3#29]
I have not explored this at all, instead just rolling back my R version to a 32-bit install, but wondered if anyone else had tackled this issue?

**Comment by SchmidtPaul** [comment]
Hi,
as far as I can tell, the [author no longer](https://twitter.com/SchmidtPaul1989/status/1657081362648555541) replies to issues. However, I just successfully ran this on my PC so there is no problem for me.

``` r
library(sankeyD3)

links <- data.frame(
  source = c(0, 0, 1, 2),
  target = c(1, 2, 3, 3),
  value = c(10, 20, 10, 20)
)

nodes <- data.frame(
  label = letters[1:4]
)

sankeyD3::sankeyNetwork(
  Links = links,
  Nodes = nodes,
  Source = "source",
  Target = "target",
  Value  = "value",
  NodeID = "label",
  numberFormat = ",.0f",
  fontFamily = "Arial",
  fontSize = 12,
  width  = 400,
  height = 300)
```

![](https://i.imgur.com/6a0TLto.png)

``` r

sessionInfo()
#> R version 4.2.2 (2022-10-31 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
#> [3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] sankeyD3_0.3.2
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.14   knitr_1.42        magrittr_2.0.3    R.cache_0.16.0   
#>  [5] R6_2.5.1          rlang_1.1.0       fastmap_1.1.1     styler_1.9.1     
#>  [9] d3r_1.0.1         tools_4.2.2       webshot_0.5.4     xfun_0.38        
#> [13] R.oo_1.25.0       cli_3.6.0         withr_2.5.0       ellipsis_0.3.2   
#> [17] htmltools_0.5.4   yaml_2.3.7        digest_0.6.31     lifecycle_1.0.3  
#> [21] processx_3.8.0    callr_3.7.3       purrr_1.0.1       ps_1.7.2         
#> [25] htmlwidgets_1.6.2 vctrs_0.6.1       R.utils_2.12.2    fs_1.6.1         
#> [29] glue_1.6.2        evaluate_0.20     rmarkdown_2.21    reprex_2.0.2     
#> [33] compiler_4.2.2    R.methodsS3_1.8.2 jsonlite_1.8.4
```

<sup>Created on 2023-05-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by todd-d-desnz** [comment]
Thanks, @SchmidtPaul, that's really helpful - I think the actual error message I had was, as per your tweet, "not available for this R version" - which I assumed was related to the switch to 64-bit. My fault for not even showing my error and not considering all the potential causes.

However, I take heart that since your tweet you seem to now have it working in R v4.2.2 x64! Did you have to do anything to make it cooperate?

**Comment by SchmidtPaul** [comment]
No, up until and including v4.2.2 I never had any problems running the package.

**Comment by todd-d-desnz** [comment]
... so today I tried again with v4.2.2 x64, and, of course, everything worked fine! Thanks for your engagement, Paul, I have no idea what I did differently, but now it all works.
