### ISSUE TITLE
export widget for static sankey client-side

### ISSUE THREAD

**Issue by timelyportfolio** [fbreitwieser/sankeyD3#3]
I just changed [`exportwidget`](https://github.com/timelyportfolio/exportwidget) to use [fabric.js](http://fabricjs.com) instead of the previously crowbar-hacked method.  I can't remember where the question was asked, but I thought it involved Sankey.  Here is the [live example](http://bl.ocks.org/timelyportfolio/a1a4ff1856d1c904613b9dee9a3b852b) of sankey + exportwidget.

**Comment by fbreitwieser** [comment]
It was @daattali in https://github.com/christophergandrud/networkD3/issues/155 . Nice update to `fabric.js`! I'll try it and add it to the documentation.

**Comment by daattali** [comment]
Thank you both!

**Comment by fbreitwieser** [comment]
Added `saveNetwork` (copied over from networkD3), which uses `htmlwidgets::saveWidget()` to export the widget
